### PR TITLE
Added Aneeka profile and contributer file

### PR DESCRIPTION
**Pull request by AneekaMari**

### CODE REVIEW

**Comment by Nihal-Priyadarshi** [comment]
> _No description provided._

Add yourself in contributors.md file then I'll merge your both requests

**Comment by Nihal-Priyadarshi** [comment]
> > _No description provided._
> 
> Add yourself in contributors.md file then I'll merge your both requests

do it asap

**Comment by Nihal-Priyadarshi** [comment]
> > > _No description provided._
> > 
> > 
> > Add yourself in contributors.md file then I'll merge your both requests
> 
> do it asap

Also write your mail id in profiles/Aneeka.md

**Comment by AneekaMari** [comment]
> > > > _No description provided._
> > > 
> > > 
> > > Add yourself in contributors.md file then I'll merge your both requests
> > 
> > 
> > do it asap
> 
> Also write your mail id in profiles/Aneeka.md

Hi sorry Done. Thank you

**Pull request merged**
