### PR TITLE
Update CONTRIBUTORS.md

### PR DESCRIPTION
**Pull request by tb-rules10**
For Hacktoberfest 2021

### CODE REVIEW

**Comment by Nihal-Priyadarshi** [comment]
You must have to complete all three tasks to get your PR merged.

**Comment by tb-rules10** [comment]
Done

**Comment by Nihal-Priyadarshi** [comment]
> Done

I'll merge this but listen don't copy from others.

**Comment by tb-rules10** [comment]
Ok i won't from next time actually I didn't knew how to write in bold or create headings.

**Pull request merged**
