### PR TITLE
Java_nextpermutation

### PR DESCRIPTION
**Pull request by RAshid602**

### CODE REVIEW

**Comment by Nihal-Priyadarshi** [comment]
> _No description provided._

You must have to include yourself in profiles folder, do it asap.

**Comment by RAshid602** [comment]
> > _No description provided._
> 
> You must have to include yourself in profiles folder, do it asap.

I am Trying to do that

**Comment by RAshid602** [comment]
> > _No description provided._
> 
> You must have to include yourself in profiles folder, do it asap.
I think i have done the task, Accept the PR 
if any conflict let me know.

**Comment by RAshid602** [comment]
> 
> You must have to include yourself in profiles folder, do it asap.

**Pull request closed without merging**
